#This is an example of train_config.yaml

# basic
random_seed: 2022
batch_size: 128
# batch_size: 50
device: cuda:0
load_checkpoint: False

# Optimizer
optimizer_name: Adam
optimizer_params:
  lr: 0.0001
  weight_decay: 0.00001

# Scheduler
# scheduler_name: MultiStepLR
# scheduler_params:
  # milestones: [5, 20, 40, 70]
  # gamma: 0.3

# Trainer
trainer_name: MCTrainer
trainer_params:
  max_epoch_num: 5
  # max_epoch_num: 10
  res_pth: f"/home/alter/"
  dataset: 'SWAT'
  # dataset: 'WADI'
  lr: 0.0001
  win_size: 105
  anomaly_ratio: 1
  index: 137
  mode: "train"
  loss_func: 'MSE'
  enable_early_stop: True
  early_stop_patience: 3 # 多少个epoch没有提升就停止训练
  early_stop_min_is_best: True # 验证集上loss是否越小越好