#This is an example of train_config.yaml

# basic
random_seed: 3407
batch_size: 10*15
device: cuda:0
load_checkpoint: False

# Optimizer
optimizer_name: Adam
optimizer_params:
  lr: 0.0001
  weight_decay: 0.0001
  params: []

metaoptimizer_name: Adam
metaoptimizer_params:
  lr: 0.001
  weight_decay: 0.0001
  params: []

# Scheduler
scheduler_name: MultiStepLR
scheduler_params:
  milestones: [5, 20, 40, 70]
  gamma: 0.3

# Trainer
trainer_name: MetaMCTrainer
trainer_params:
  max_epoch_num: 5
  window: 5
  thresh: 0.8
  hyper_c: 0.5
  enable_early_stop: True
  early_stop_patience: 3 # 多少个epoch没有提升就停止训练
  early_stop_min_is_best: True # 验证集上loss是否越小越好