random_seed: 3426 #3407
batch_size: 64
device: cuda:0
load_checkpoint: False

# Optimizer
optimizer_name: Adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001

# Scheduler
scheduler_name: MultiStepLR
scheduler_params:
  milestones: [600]
  gamma: 0.3

# Trainer
trainer_name: MLPTrainer
trainer_params:
  max_epoch_num: 50
  enable_early_stop : True
  early_stop_patience : 50
  early_stop_min_is_best : True
