#This is an example of train_config.yaml

# basic
random_seed: 2023
batch_size: 32
device: cuda:0
load_checkpoint: False

# Optimizer
optimizer_name: Adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001

# Scheduler
scheduler_name: MultiStepLR
scheduler_params:
  milestones: [5, 20, 40, 70]
  gamma: 0.3

# Trainer
trainer_name: KoopaTrainer_0
trainer_params:
  max_epoch_num: 80
  early_stop: 10
  use_amp: False
  patience: 3
  batch_size: 32
  learning_rate: 0.001
  lradj: 'type1'
  online_learning: 'full'
  n_inner: 1
  inverse: False