#This is an example of train_config.yaml

# basic
random_seed: 3407
batch_size: 128
device: cuda:0
load_checkpoint: False

# Optimizer
optimizer_name: Adam
optimizer_params:
  lr: 0.0005
  weight_decay: 1.0e-5
  eps: 1.0e-8

# Scheduler
scheduler_name: MultiStepLR
scheduler_params:
  milestones: [ 1, 18, 36, 54, 72 ]
  gamma: 0.5


# Trainer
trainer_name: STDMAETrainer
trainer_params:
  max_epoch_num: 80
  early_stop: 10
  skip_pretrain: False
  pretrain_model_name: STDNoise
  pretrain_model_params:
    s_model_params:
      patch_size: 20
      in_channel: 1
      embed_dim: 96
      num_heads: 4
      mlp_ratio: 4
      dropout: 0.1
      low_rank: 10
      low_rank_method: ae
      patch_method: STpatch
      adjust_adj_mx: true
      mix_function: add
      ae_low_rank_hidden_list: [ 64, 32 ]
      noise_type: [ 'gaussian', 'uniform' ]
      noise_intensity: {
        'gaussian': {
          'mean': 0,    # 噪声的均值
          'std': 0.1    # 噪声的标准差
        },
        'uniform': {
          'a': -0.2,    # 均匀分布的下界
          'b': 0.2      # 均匀分布的上界
        },
        'salt_pepper': {
          'prob': 0.05,     # 像素变为盐或胡椒的概率
          'salt_val': 1,    # 盐的值
          'pepper_val': 0   # 胡椒的值
        },
        'sine': {
          'freq': 1,    # 正弦波的频率
          'amp': 1,     # 正弦波的振幅
          'phase': 0    # 正弦波的相位
        },
        'random_walk': {
          'step_std': 1     # 每一步的标准差
        }
      }
      encoder_depth: 4
      decoder_depth: 1
      spatial: True
      mode: pre-train

    t_model_params:
      patch_size: 20
      in_channel: 1
      embed_dim: 96
      num_heads: 4
      mlp_ratio: 4
      low_rank: 10
      low_rank_method: ae
      patch_method: STpatch
      adjust_adj_mx: true
      mix_function: add
      ae_low_rank_hidden_list: [ 64, 32 ]
      dropout: 0.1
      noise_type: [ 'gaussian', 'uniform' ]
      noise_intensity: {
        'gaussian': {
          'mean': 0,    # 噪声的均值
          'std': 0.1    # 噪声的标准差
        },
        'uniform': {
          'a': -0.2,    # 均匀分布的下界
          'b': 0.2      # 均匀分布的上界
        },
        'salt_pepper': {
          'prob': 0.05,     # 像素变为盐或胡椒的概率
          'salt_val': 1,    # 盐的值
          'pepper_val': 0   # 胡椒的值
        },
        'sine': {
          'freq': 1,    # 正弦波的频率
          'amp': 1,     # 正弦波的振幅
          'phase': 0    # 正弦波的相位
        },
        'random_walk': {
          'step_std': 1     # 每一步的标准差
        }
      }
      encoder_depth: 4
      decoder_depth: 1
      spatial: False
      mode: pre-train

  pretrainer_params:
    optimizer_name: Adam
    optimizer_params:
      s_model_params:
        lr: 0.0005
        weight_decay: 1.0e-5
        eps: 1.0e-8
      t_model_params:
        lr: 0.0005
        weight_decay: 1.0e-5
        eps: 1.0e-8
    # Scheduler
    scheduler_name: MultiStepLR
    scheduler_params:
      s_model_params:
        milestones: [ 3, 7, 15, 25 ]
        gamma: 0.5
      t_model_params:
        milestones: [ 3, 7, 15, 25 ]
        gamma: 0.5
    #Pretrainer
    trainer_name: IDAEPretrainer
    trainer_params:
      max_epoch_num: 30
      early_stop: 10
