#This is an example of train_config.yaml

# basic
random_seed: 3
batch_size: 8000
device: cuda:0
load_checkpoint: False

# Optimizer
optimizer_name: Adam
optimizer_params:
  lr: 0.001
  weight_decay: 0

# Scheduler
scheduler_name: MultiStepLR
scheduler_params:
    milestones: [5, 20, 40, 70]
    gamma: 0.3

# Trainer
trainer_name: USADTrainer
trainer_params:
  max_epoch_num: 100
  res_pth: f"/home/alter/"
  enable_early_stop: False
  early_stop_patience: 10 # 多少个epoch没有提升就停止训练
  early_stop_min_is_best: True # 验证集上loss是否越小越好