CSTAGNN_stamp:
  n_layer: 1
  n_attr: 32
  n_hid: 256
  reg_A: 0.0001
  circle: 288 #12*24
  drop_prob: 0.2
  n_c: 10
  a: 0.1
  n_mask: 1
  adj_mx: None

  # expand attr by conv
  CE:
    use: True
    kernel_size: 1
    bias: False
  # expand attr by linear
  LE:
    use: False
    bias: False
  # spatio encoding
  SE:
    use: True
    separate: True
    nor: False
  # tempo encoding
  TE:
    use: True
    nor: True

  # MultiHeadAttention
  attn:
    head: 1
    d_k: 32
    d_v: 32
    drop_prob: 0.2

  # TPGNN polynomial order
  STstamp:
    use: True
    kt: 3
    temperature: 1.0

  T4N:
    'use': True
    'step': 2
    'end_epoch': 10000
    'change_head': True
    'change_enc': True