NS:
  enc_in: 21
  dec_in: 21
  c_out: 21
  dropout: 0.05
  seg_len: 48
  e_layers: 2
  d_layers: 1
  factor: 3
  embed: 'timeF'
  d_model: 512
  output_attention: False
  p_hidden_layers: 2
  n_heads: 8
  activation: 'gelu'
  p_hidden_dims: [256, 256]
  d_ff: 2048

