# This is an example of model_config.yaml

LSTM:
  hidden_lstm: 256
  num_layer_lstm: 2
  hidden_fc: [64, 16]
  bi: False
  dropout: 0.2

ASTGCN:
  num_block: 2
  kernel_size: 3
  num_cheb_filter: 64
  num_time_filter: 64
  stride: 1
  padding: 0
  conv_type: cheb
  K: 2

StemGNN:
  stack_cnt: 2
  dropout_rate: 0.5
  leaky_rate: 0.2
  multi_layer: 5

AGCRN:
  rnn_units: 64,
  num_layers: 2,
  default_graph: True,
  embed_dim: 10,
  cheb_k: 2

AutoFormer:
  factor: 3,                                # attn factor
  d_model: 512,
  moving_avg: 25,                           # window size of moving average. This is a CRUCIAL hyper-parameter.
  n_heads: 8,
  e_layers: 2,                              # num of encoder layers
  d_layers: 1,                              # num of decoder layers
  d_ff: 2048,
  dropout: 0.05,
  output_attention: False,
  embed: timeF,                           # [timeF, fixed, learned]
  activation: gelu,
  num_time_features: 4,                     # number of used time features
  time_of_day_size: 24 * 4,
  day_of_week_size: 7,
  day_of_month_size: 31,
  day_of_year_size: 366

Crossformer:
  seg_len: 24,
  win_size: 2,
  # default parameters
  factor: 10,
  d_model: 256,
  d_ff: 512,
  n_heads: 4,
  e_layers: 3,
  dropout: 0.2,
  baseline: False
