# This is an example of data_config.yaml

# data_preprocessors
data_preprocessor_name: MCDataPreprocessor
data_preprocessor_params:
  data_path: '/home/ICDC/data/SWaT/'
  # data_path: '/home/ICDC/data/WADI/'
  win_size: 100
  step: 1
  dataset: 'SWAT'
  # dataset: 'WADI'
  mode: "train"
  dist: 0
  ret_data: False

dataloader_params:
  num_workers: 8
  pin_memory: True
  drop_last: False