# This is an example of data_config.yaml

# data_preprocessors
data_preprocessor_name: ETTh2DataPreprocessor
data_preprocessor_params:
  data_path: data/pems-bay.csv
  train_ratio: 0.2
  valid_ratio: 0.05
  adj_mx_path: None
  history_len: 12
  forecast_len: 12
  timeenc: 2
  freq: 'h'


# Scaler
scaler_name: StandardScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataset_name: ETTh2Dataset
dataset_params: {}


dataloader_params:
  train:
    shuffle: True
    num_workers: 0
    pin_memory: True
    drop_last: True
  valid:
    shuffle: False
    num_workers: 0
    pin_memory: True
    drop_last: False
  test:
    shuffle: False
    num_workers: 0
    pin_memory: True
    drop_last: False


