data_preprocessor_name: JNUDataPreprocessor
data_preprocessor_params:
  data_path: ./data/JNU
  train_ratio: 0.7
  valid_ratio: 0.15
  s_load: 0
  t_load: 1
  label_dict : ['n','ib','tb','ob']
  domain_dict: ['600','800','1000']
  data_dict: { 0:['ib600_2.csv','n600_2.csv','ob600_2.csv','tb600_2.csv'],
               1:['ib800_2.csv','n800_2.csv','ob800_2.csv','tb800_2.csv'],
               2:['ib1000_2.csv','n1000_2.csv','ob1000_2.csv','tb1000_2.csv']
               }
  s_label_set: [ 0,1,2,3]
  t_label_set: [ 0,1,2,3]
  # data names in every working conditions
  number_class: 4 
  fft: False
  data_length: 1600
  window: 512
  random_seed: 29
  data_dimension : '1D'
  class_num : 4


# Scaler
scaler_name: DWTMinMaxScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataloader_params:
  shuffle: True
  num_workers: 0
  pin_memory: True
  drop_last: False
