# This is an example of data_config.yaml

# data_preprocessors
data_preprocessor_name: LargeSTDataPreprocessor
data_preprocessor_params:
  data_path: data/regression_dataset/GBA/GBA.h5
  adj_mx_path: data/regression_dataset/GBA/adj_GBA.npy
  train_ratio: 0.6
  valid_ratio: 0.2
  steps_per_day: 1
  add_feature_time_of_day: True
  add_feature_day_of_week: True
  add_feature_day_of_month: True
  add_feature_day_of_year: True


# Scaler
scaler_name: StandardScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataset_name: MultiStepForecastDataset
dataset_params:
  history_len: 12
  forecast_len: 12

dataloader_params:
  shuffle: False
  num_workers: 0
  pin_memory: True
  drop_last: False
