
# Scaler
scaler_name: StandardScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataset_name: CMAPSSDataset
dataset_params:
  data_path: "./data"
  sub_dataset: "FD004"
  validation_rate : 0.2
  use_only_final_on_test : True
  use_max_rul_on_test : True
  batch_size : 128
  sequence_len: 30
  max_rul: 125
  norm_type: '0-1'
  include_cols: None
  exclude_cols: None
  cluster_operations: True
  norm_by_operations: True
  return_sequence_label: False
  return_id: True
  emd : True
  emd_num : 2

dataloader_params:
  shuffle: False
  num_workers: 0
  pin_memory: True
  drop_last: False
