# This is an example of data_config.yaml

# data_preprocessors
data_preprocessor_name: PEMSD7DataPreprocessor
data_preprocessor_params:
  data_path: data/PEMSD7.csv
  train_ratio: 0.772727272727 #34/44
  valid_ratio: 0.113636363636 #5/44
  adj_mx_path: data/PEMSD7_adj_mx.csv
  stamp_path : data/PEMSD7_time_stamp.npy
  history_len: 12
  forecast_len: 12
  eps: 0.1


# Scaler
scaler_name: StandardScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataset_name: PEMSD7Dataset
dataset_params:
  day_slot: 288
  num_route: 228
  T4N_step: 2

dataloader_params: #和原论文中有些区别，后面可以改
  train:
    shuffle: True
    num_workers: 0
    pin_memory: True
    drop_last: False
  valid:
    shuffle: True
    num_workers: 0
    pin_memory: True
    drop_last: False
  test:
    shuffle: True
    num_workers: 0
    pin_memory: True
    drop_last: False