# This is an example of data_config.yaml

# data_preprocessors
data_preprocessor_name: PUDataPreprocessor
data_preprocessor_params:
  data_path: data/PU
  train_ratio: 0.7
  valid_ratio: 0.15
  s_load: 0
  t_load: 1
  s_label_set: [ 0,1,2,3 ]
  t_label_set: [ 0,1,2,3 ]
  class_num: 4
  feature_name: _DE_time
  work_state : ["N15_M07_F10", "N09_M07_F10", "N15_M01_F10", "N15_M07_F04"]
  # data names in fault type
  name_dict: {0:["K001", "K002", "K003", "K004", "K005", "K006"],   # normal
              1:["KI04", "KI14", "KI16", "KI17", "KI18", "KI21"],   # IF
              2:["KA04", "KA15", "KA16", "KA22", "KA30"],           # OF
              3:["KB23", "KB24", "KB27"]}                           # MF
  fft: False
  data_length: 4096
  window: 2048
  random_seed: 29
  data_dimension : "1D"


# Scaler
scaler_name: MinMaxScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataloader_params:
  shuffle: True
  num_workers: 0
  pin_memory: True
  drop_last: False
