# This is an example of data_config.yaml

# data_preprocessors
data_preprocessor_name: WeatherDataPreprocessor
data_preprocessor_params:
  data_path: data/regression_dataset/Weather/Weather.csv
  adj_mx_path: Nonullne
  steps_pre_day: 288
  train_ratio: 0.7
  valid_ratio: 0.1
  add_feature_time_of_day: True
  add_feature_day_of_week: True
  add_feature_day_of_month: True
  add_feature_day_of_year: True


# Scaler
scaler_name: StandardScaler
scaler_params:
  mean: 0
  std: 1

# Dataset
dataset_name: MultiStepForecastDataset
dataset_params:
  history_len: 96
  forecast_len: 336

dataloader_params:
  shuffle: False
  num_workers: 0
  pin_memory: True
  drop_last: False
